version: "3"
services:
  client:
    build: .
    # ports:
    # - 0.0.0.0:3011:80
    volumes:
      - ./public/dog.jpg:/usr/share/nginx/html/dog.jpg

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
    - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=reactdemo.duckdns.org
      - VALIDATION=duckdns
      - STAGING=false
    volumes:
      - /home/alex/data/swag:/config
      - ./default.conf:/config/nginx/site-confs/default.conf
    ports:
    - 0.0.0.0:3011:443 
    restart: unless-stopped