name: Deploy react
env: 
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
on: [push, workflow_dispatch]
jobs:
  deploy-application:
    runs-on: [ self-hosted ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          cd larger-project

          docker build -t alex_eslint -f eslint.Dockerfile .
          docker run -i --rm alex_eslint

          docker compose pull
          docker compose build
          docker compose down
          docker compose up -d