name: Update home server containers
env: 
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
on: [push, workflow_dispatch]
jobs:
  deploy-application:
    runs-on: [ office-server ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          cd larger-project
          docker compose pull
          docker compose build
          docker compose up -d