name: Update home server containers
on: [push, workflow_dispatch]
jobs:
  deploy-application:
    runs-on: [self-hosted, office-server]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          cd larger-project
          docker compose pull
          docker compose build
          docker compose up -d