GET http://localhost:8080/realms/demo/.well-known/openid-configuration

###
# create challenge: echo -n "randomsecretstringrandomsecretstringrandomsecretstringrandomsecretstring" | sha256sum -b | xxd -p -r | base64 | tr '/+' '_-' | tr -d '='
# code_challenge: gR16hjqNRs3ofOuVtlHGwabDPymJQYT8sJ1UxnW09qk
# i think code_verifier has lenght requirements

# Simulate sending user's browser to this endpoint
# @name first

GET http://localhost:8080/realms/demo/protocol/openid-connect/auth
    ?client_id=my-client
    &redirect_uri=http://doestntExist/callback
    &response_type=code
    &response_mode=fragment
    &state=random-response-string
    &code_challenge=gR16hjqNRs3ofOuVtlHGwabDPymJQYT8sJ1UxnW09qk
    &code_challenge_method=S256
    &scope=openid+profile

### still pretenting to be the users browswer submitting form
### get url from action of previous form
### & is going to be html escaped
# @name manualLogin
POST http://localhost:8080/realms/demo/login-actions/authenticate
    ?session_code=HYKUrEXYvaHGFGrrzlcEIjxy-YjrwAQasYs0Q5sH--Q
    &execution=7e86d80e-c6d0-45a4-b5e8-cf042abd2c86
    &client_id=my-client
    &tab_id=sf89CjGkkOk
Content-Type: application/x-www-form-urlencoded
Cookie: {{first.response.headers.Set-Cookie}}

username=user
&password=password


# state=random-response-string
# &session_state=4c25d8d0-7659-47c3-90d6-4b5198c3857c
# &code=bc414068-1f87-4274-8940-51b5f86ec05e.4c25d8d0-7659-47c3-90d6-4b5198c3857c.e655ac6a-4f3a-40cb-975a-d4886654f1ec

### get data out of manualLogin Location header (redirecting back to the application in browser)
### session state parameter 
# @name getToken
post http://localhost:8080/realms/demo/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=my-client
&code=4f61d9d7-f655-4a3b-bd36-2a2b62da15d7.60aad427-6351-4968-b15b-29fae3b9b8a9.e655ac6a-4f3a-40cb-975a-d4886654f1ec
&code_verifier=randomsecretstringrandomsecretstringrandomsecretstringrandomsecretstring
&redirect_uri=http://doestntExist/callback
&grant_type=authorization_code

###

# @name useToken

GET http://localhost:8080/realms/demo/protocol/openid-connect/userinfo
Authorization: Bearer {{getToken.response.body.access_token}}